import {futureSafeAt,normalSaleAt,megaSaleAt,megaPoAt,timeSaleAt,rakutenAt,solve,num} from './core.mjs';

const defaults={
  activePlatform:'mega-sale',
  normalSale:{targetProfit:100,productCost:858,sellerShippingCost:220,categoryFeeRate:10,feeTaxRate:10,timeSaleRate:5,listingFee:0,expectedOrders:1},
  megaSale:{targetProfit:100,productCost:4034,sellerShippingCost:450,customerShipping:0,categoryFeeRate:10,buyerDiscountRate:20,sellerDiscountShare:50,megaSystemFeeRate:1,supportFeeRate:.5,feeTaxRate:10,discountCap:10000},
  megaPo:{targetProfit:50,productCost:858,sellerShippingCost:0,customerShipping:0,categoryFeeRate:10,couponRate:10,sellerCouponShare:50,pointRate:10,sellerPointShare:50,feeTaxRate:10,couponCap:10000,pointCap:10000},
  timeSale:{targetProfit:100,productCost:858,sellerShippingCost:0,customerShipping:0,optionPrice:0,categoryFeeRate:10,feeTaxRate:10,discountType:'rate',discountRate:10,discountAmount:100,listingFee:0,expectedOrders:1},
  rakuten:{targetProfit:70,productCostPerUnit:6820,sellerShippingCost:220,customerShipping:0,quantity:1,pointMultiplier:1,productTaxRate:10,fixedCostPerOrder:0,rmsRate:4.5,rakutenPayRate:3.5,safetyRate:.1,otherVariableRate:0,feeTaxRate:10,oneItemCouponRate:2,twoItemCoupon:100,threeItemCoupon:150,fourItemCoupon:200,priorCouponUses:50,couponFeeThreshold:50,couponSystemFeePreTax:50}
};
const root=document.querySelector('#root');let state=load();
const money=(v,d=false)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',minimumFractionDigits:0,maximumFractionDigits:d?1:0}).format(v);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function load(){try{const old=JSON.parse(localStorage.getItem('ec-price-calculator-v1')||'{}'),hasStrategy=old.normalSale&&Object.prototype.hasOwnProperty.call(old.normalSale,'timeSaleRate');return{activePlatform:hasStrategy?(old.activePlatform||'normal-sale'):'normal-sale',normalSale:{...defaults.normalSale,...old.normalSale},megaSale:{...defaults.megaSale,...old.megaSale},megaPo:{...defaults.megaPo,...old.megaPo},timeSale:{...defaults.timeSale,...old.timeSale},rakuten:{...defaults.rakuten,...old.rakuten}}}catch{return structuredClone(defaults)}}
const save=()=>localStorage.setItem('ec-price-calculator-v1',JSON.stringify(state));
const field=(g,k,label,suffix='円',hint='',step=1)=>`<label class="field"><span class="field-label">${label}</span><span class="input-wrap"><input data-group="${g}" data-key="${k}" inputmode="decimal" min="0" step="${step}" type="number" value="${esc(state[g][k])}"><span class="input-suffix">${suffix}</span></span>${hint?`<span class="field-hint">${hint}</span>`:''}</label>`;
const row=(label,value,accent=false,decimal=false)=>`<div class="breakdown-row${accent?' accent':''}"><span>${label}</span><strong>${money(value,decimal)}</strong></div>`;
const pointRow=(label,value)=>`<div class="breakdown-row"><span>${label}</span><strong>${Math.round(value).toLocaleString('ja-JP')} Point</strong></div>`;
function panel(group,title,primary,advanced,tip,extra=''){return`<section class="input-column"><div class="section-title"><div><p class="step-label">STEP 1</p><h2>${title}</h2></div><button class="reset-button" data-reset="${group}" type="button">恢复默认</button></div>${extra}<div class="field-grid">${primary}</div><details class="advanced"><summary>平台活动参数</summary><div class="field-grid">${advanced}</div></details><div class="rule-tip">${tip}</div></section>`}
function result(title,label,r,target,note,rows,decimal=false){const price=r.listPrice??r.orderPrice;return`<aside class="result-column" aria-live="polite"><section class="result-card"><div class="result-eyebrow"><span>${title}</span><span class="status-dot">已达目标</span></div><p class="result-label">${label}</p><p class="result-price">${money(price,decimal)}</p><p class="result-caption">已逐个整数售价复核，利润不低于 ${money(target)}</p><div class="quick-metrics"><div><span>买家支付</span><strong>${money(r.buyerPayment,decimal)}</strong></div><div><span>卖家结算</span><strong>${money(r.settlement,decimal)}</strong></div><div><span>实际利润</span><strong>${money(r.profit,decimal)}</strong></div></div><div class="relation-note info">${note}</div><h3>金额拆解</h3><div class="breakdown">${rows}</div><button class="copy-button" type="button" data-copy="${esc(`${title}\n建议售价：${money(price,decimal)}\n买家支付：${money(r.buyerPayment,decimal)}\n卖家结算：${money(r.settlement,decimal)}\n实际利润：${money(r.profit,decimal)}`)}">复制计算结果</button></section></aside>`}

function megaSaleView(){const p=state.megaSale,r=solve(megaSaleAt,p);return panel('megaSale','填写每单成本',field('megaSale','targetProfit','目标利润')+field('megaSale','productCost','商品成本')+field('megaSale','sellerShippingCost','卖家实际物流成本','円','你实际支付给物流公司的运费')+field('megaSale','customerShipping','向顾客收取的送料','円','包邮填 0；会计入买家订单支付')+field('megaSale','categoryFeeRate','类目手续费率','%','',.1),field('megaSale','buyerDiscountRate','买家优惠率','%','',.1)+field('megaSale','sellerDiscountShare','卖家承担比例','%','',.1)+field('megaSale','megaSystemFeeRate','Mega割系统利用料','%','',.1)+field('megaSale','supportFeeRate','折扣支援手续费','%','',.1)+field('megaSale','feeTaxRate','平台手续费消费税','%','',.1)+field('megaSale','discountCap','单张优惠上限'),'<strong>计算口径</strong><span>商品标价不含另收送料；买家实付＝优惠后商品金额＋顾客送料。</span>')+result('Qoo10 Mega割','最低建议商品标价',r,p.targetProfit,'买家实付包含另收送料；卖家结算与买家支付是不同口径。',row('商品标价',r.listPrice)+row('－ 买家 Mega割优惠',-r.discount)+row('＋ 顾客送料',p.customerShipping)+row('＝ 买家订单支付',r.buyerPayment,true)+row('－ 类目手续费',-r.categoryFee)+row('－ 卖家优惠负担',-r.sellerDiscount)+row('－ 系统费与支援费',-(r.systemFee+r.supportFee))+row('－ 手续费消费税',-r.feeTax)+row('＝ 卖家最终结算',r.settlement,true))}
function normalSaleView(){const p=state.normalSale,plan={...p,mega:{...state.megaSale,productCost:p.productCost,sellerShippingCost:p.sellerShippingCost},po:{...state.megaPo,productCost:p.productCost,sellerShippingCost:p.sellerShippingCost}},r=solve(futureSafeAt,plan);const advanced=`<details class="advanced"><summary>活动预案 · 默认预留 5% Time Sale</summary><div class="field-grid">${field('normalSale','timeSaleRate','预定 Time Sale 折扣率','%','至少 1%；高利润商品可适当提高',.1)+field('normalSale','listingFee','本次展示费','Q-Cash','仅设置折扣、不购买展示填 0')+field('normalSale','expectedOrders','预计本时段订单数','单','用于分摊固定展示费')}</div></details>`;const input=`<section class="input-column"><div class="section-title"><div><p class="step-label">STEP 1</p><h2>长期安全定价</h2></div><button class="reset-button" data-reset="normalSale" type="button">恢复默认</button></div><div class="field-grid normal-fields">${field('normalSale','productCost','商品成本')+field('normalSale','sellerShippingCost','实际运费','円','你支付给物流公司的费用')+field('normalSale','targetProfit','活动期最低目标利润')}</div>${advanced}<div class="rule-tip"><strong>一价覆盖未来活动</strong><span>系统同时校验正常销售、Mega割＋Time Sale、MegaPo＋Time Sale，并采用最不利场景反推长期标价。</span></div></section>`;const note=`当前最不利场景：${r.worstName}。Time Sale 后价格 ${money(r.mega.timeSalePrice)}；无需在活动前临时涨价。`;const rows=row('建议长期日常标价',r.listPrice,true)+row(`－ Time Sale ${p.timeSaleRate}%`,-r.mega.timeDiscount)+row('＝ Time Sale 展示价',r.mega.timeSalePrice,true)+row('正常销售利润',r.normal.profit)+row('Mega割＋Time Sale 买家支付',r.mega.buyerPayment)+row('Mega割＋Time Sale 利润',r.mega.profit,true,true)+row('MegaPo＋Time Sale 买家支付',r.po.buyerPayment)+pointRow('MegaPo 买家另获',r.po.points)+row('MegaPo＋Time Sale 利润',r.po.profit,true,true);return input+result('Qoo10 长期安全定价','建议长期日常标价',r,p.targetProfit,note,rows,true)}
function megaPoView(){const p=state.megaPo,r=solve(megaPoAt,p);return panel('megaPo','填写每单成本',field('megaPo','targetProfit','目标利润')+field('megaPo','productCost','商品成本')+field('megaPo','sellerShippingCost','卖家实际物流成本')+field('megaPo','customerShipping','向顾客收取的送料','円','Point 不会从本次实付再次扣除')+field('megaPo','categoryFeeRate','类目手续费率','%','',.1),field('megaPo','couponRate','Coupon 优惠率','%','',.1)+field('megaPo','sellerCouponShare','卖家 Coupon 承担','%','',.1)+field('megaPo','pointRate','Point 付与率','%','',.1)+field('megaPo','sellerPointShare','卖家 Point 承担','%','',.1)+field('megaPo','feeTaxRate','平台手续费消费税','%','',.1)+field('megaPo','couponCap','Coupon 优惠上限')+field('megaPo','pointCap','Point 付与上限'),'<strong>端数处理</strong><span>Point 四舍五入；奇数 Point 的多出 1 円由 Qoo10 承担。</span>')+result('Qoo10 MegaPo','最低建议商品标价',r,p.targetProfit,`买家本次支付不扣 Point；另获 ${r.points.toLocaleString('ja-JP')} Point。`,row('商品标价',r.listPrice)+row('－ Coupon 优惠',-r.coupon)+row('＋ 顾客送料',p.customerShipping)+row('＝ 买家订单支付',r.buyerPayment,true)+row('买家另获 Point',r.points)+row('－ 类目手续费',-r.categoryFee)+row('－ 卖家 Coupon 负担',-r.sellerCoupon)+row('－ 卖家 Point 负担',-r.sellerPoints)+row('－ 手续费消费税',-r.feeTax)+row('＝ 卖家最终结算',r.settlement,true))}

function timeSaleView(){const p=state.timeSale,r=solve(timeSaleAt,p);const mode=`<div class="scenario-card"><div class="segment-field"><span class="field-label">折扣输入方式</span><div class="segment"><button class="${p.discountType==='rate'?'active':''}" data-select="discountType" data-value="rate" type="button">按比例</button><button class="${p.discountType==='amount'?'active':''}" data-select="discountType" data-value="amount" type="button">按金额</button></div></div><div class="segment-field"><span class="field-label">展示方案</span><div class="segment listing-segment">${[['0','仅折扣 · 免费'],['2000','Standard · 2,000'],['5000','Premium T0/T1 · 5,000'],['6000','Premium T2 · 6,000']].map(([v,l])=>`<button class="${num(p.listingFee)===num(v)?'active':''}" data-select="listingFee" data-value="${v}" type="button">${l}</button>`).join('')}</div></div></div>`;const discountField=p.discountType==='amount'?field('timeSale','discountAmount','Time Sale 折扣金额'):field('timeSale','discountRate','Time Sale 折扣率','%','至少 1%',.1);const input=panel('timeSale','填写 Time Sale 条件',field('timeSale','targetProfit','目标利润')+field('timeSale','productCost','商品成本')+field('timeSale','sellerShippingCost','卖家实际物流成本')+field('timeSale','customerShipping','向顾客收取的送料')+field('timeSale','optionPrice','选项追加价格','円','选项价参与手续费计算')+field('timeSale','categoryFeeRate','类目手续费率','%','',.1),discountField+field('timeSale','feeTaxRate','平台手续费消费税','%','',.1)+field('timeSale','listingFee','本次展示费','Q-Cash','免费设置填 0')+field('timeSale','expectedOrders','预计本时段订单数','单','用于把固定展示费分摊到每单'),'<strong>官方精算口径</strong><span>Time Sale 折扣由卖家承担；类目手续费仍按折扣前价格＋选项价＋顾客送料计算。有料展示费为固定广告费，本页按预计订单数分摊。</span>',mode);const eligibility=r.eligible?'符合至少 1% 的活动折扣要求。':`当前实际折扣 ${r.actualDiscountRate.toFixed(2)}%，不符合至少 1% 的要求。`;return input+result('Qoo10 Time Sale','最低建议通常商品价格',r,p.targetProfit,`${eligibility} Time Sale 展示价为 ${money(r.salePrice)}；每单广告分摊 ${money(r.adCostPerOrder,true)}。`,row('通常商品价格',r.listPrice)+row('－ Time Sale 折扣',-r.discount)+row('＋ 选项追加价格',r.optionPrice)+row('＋ 顾客送料',r.shipping)+row('＝ 买家订单支付',r.buyerPayment,true)+row('手续费计算基数',r.commissionBase)+row('－ 类目手续费',-r.categoryFee)+row('－ 手续费消费税',-r.feeTax)+row('－ 每单展示费分摊',-r.adCostPerOrder,false,true)+row('＝ 卖家结算（广告后）',r.settlement,true,true),true)}

function rakutenView(){const p=state.rakuten,r=solve(rakutenAt,p);const scenario=`<div class="scenario-card"><div class="segment-field"><span class="field-label">积分倍率</span><div class="segment">${[1,2,5].map(v=>`<button class="${p.pointMultiplier===v?'active':''}" data-rakuten="pointMultiplier" data-value="${v}" type="button">${v} 倍</button>`).join('')}</div></div><div class="segment-field"><span class="field-label">购买件数</span><div class="segment">${[1,2,3,4].map(v=>`<button class="${p.quantity===v?'active':''}" data-rakuten="quantity" data-value="${v}" type="button">${v} 件</button>`).join('')}</div></div></div>`;return panel('rakuten','选择订单方案',field('rakuten','targetProfit','目标利润')+field('rakuten','productCostPerUnit','单件商品成本')+field('rakuten','sellerShippingCost','卖家实际物流成本')+field('rakuten','customerShipping','向顾客收取的送料')+field('rakuten','fixedCostPerOrder','每单固定成本'),field('rakuten','rmsRate','RMS 系统利用料率','%','',.1)+field('rakuten','rakutenPayRate','乐天 Pay 利用料率','%','',.1)+field('rakuten','safetyRate','安全预留费率','%','',.1)+field('rakuten','otherVariableRate','其他变动费率','%','',.1)+field('rakuten','productTaxRate','商品消费税率','%','',.1)+field('rakuten','feeTaxRate','平台费消费税率','%','',.1)+field('rakuten','oneItemCouponRate','1 件 Coupon 率','%','',.1)+field('rakuten','twoItemCoupon','2 件 Coupon')+field('rakuten','threeItemCoupon','3 件 Coupon')+field('rakuten','fourItemCoupon','4 件 Coupon')+field('rakuten','priorCouponUses','本月已用 Coupon 数','次')+field('rakuten','couponFeeThreshold','Coupon 系统费起算数','次')+field('rakuten','couponSystemFeePreTax','Coupon 系统费（税前）'),'<strong>使用提醒</strong><span>乐天费率随套餐和月度档位变化，请按 RMS 账单调整。</span>',scenario)+result(`乐天 · ${p.quantity} 件 · ${p.pointMultiplier} 倍积分`,'最低建议订单商品总价',r,p.targetProfit,`单件建议价 ${money(r.unitPrice,true)}；买家获得 ${r.buyerPoints.toLocaleString('ja-JP')} Point。`,row('商品总价',r.orderPrice)+row('－ Coupon 优惠',-r.coupon)+row('＋ 顾客送料',p.customerShipping)+row('＝ 买家订单支付',r.buyerPayment,true)+row('－ 买家 Point 原资',-r.buyerPoints)+row('－ RMS 系统利用料',-r.rmsFee,false,true)+row('－ 乐天 Pay 利用料',-r.payFee,false,true)+row('－ 其他费用',-(r.otherFee+r.couponSystemFee),false,true)+row('＝ 扣平台费后金额',r.settlement,true,true),true)}

function render(){const views={'normal-sale':normalSaleView,'mega-sale':megaSaleView,'mega-po':megaPoView,'time-sale':timeSaleView,rakuten:rakutenView};root.innerHTML=`<div class="app-shell"><header class="hero"><div class="brand-mark">算</div><div><p class="kicker">手机端售价反推工具</p><h1>跨境电商售价计算器</h1><p class="hero-copy">先定长期安全价，再参加 Mega割、MegaPo 与 Time Sale。</p></div><div class="local-badge">数据仅保存在本机</div></header><nav class="platform-tabs">${[['normal-sale','长期安全定价','兼容未来活动'],['mega-sale','Qoo10 Mega割','20% 优惠'],['mega-po','Qoo10 MegaPo','Coupon＋积分'],['time-sale','Qoo10 Time Sale','时段折扣'],['rakuten','乐天市场','多件组合']].map(([id,l,s])=>`<button class="${state.activePlatform===id?'active':''}" data-tab="${id}" type="button"><strong>${l}</strong><span>${s}</span></button>`).join('')}</nav><main class="calculator-layout">${views[state.activePlatform]()}</main><section class="sources"><div><p class="step-label">RULE CHECK</p><h2>规则依据与使用提醒</h2></div><p>页面按 2026-08-29 可公开查到的规则制作。各店铺合同、类目及活动期设置可能不同，最终请以你的 QSM／RMS 后台明细为准。</p><div class="source-links"><a href="https://doc.image-qoo10.jp/sqm/JP/guide_timesale_JP.compressed.pdf" target="_blank" rel="noreferrer">Qoo10 Time Sale 官方指南</a><a href="https://article-university.qoo10.jp/entry/98" target="_blank" rel="noreferrer">Qoo10 广告与促销</a><a href="https://university.qoo10.jp/faq/" target="_blank" rel="noreferrer">Qoo10 手续费 FAQ</a><a href="https://article-university.qoo10.jp/entry/183" target="_blank" rel="noreferrer">Qoo10 Mega割说明</a><a href="https://article-university.qoo10.jp/entry/72" target="_blank" rel="noreferrer">Qoo10 MegaPo 结算</a><a href="https://www.rakuten.co.jp/ec/plan/" target="_blank" rel="noreferrer">乐天出店费用</a></div></section><footer><span>跨境电商售价计算器</span><span>自动保存 · 手机优先 · 日元计算</span></footer></div>`;bind()}
function bind(){root.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{state.activePlatform=el.dataset.tab;save();render()});root.querySelectorAll('input[data-group]').forEach(el=>{el.onfocus=()=>el.select();el.onchange=()=>{state[el.dataset.group][el.dataset.key]=Math.max(0,num(el.value));save();render()}});root.querySelectorAll('[data-reset]').forEach(el=>el.onclick=()=>{state[el.dataset.reset]=structuredClone(defaults[el.dataset.reset]);save();render()});root.querySelectorAll('[data-select]').forEach(el=>el.onclick=()=>{const k=el.dataset.select;state.timeSale[k]=k==='discountType'?el.dataset.value:num(el.dataset.value);save();render()});root.querySelectorAll('[data-rakuten]').forEach(el=>el.onclick=()=>{state.rakuten[el.dataset.rakuten]=num(el.dataset.value);save();render()});root.querySelectorAll('[data-copy]').forEach(el=>el.onclick=async()=>{try{await navigator.clipboard.writeText(el.dataset.copy);toast('已复制')}catch{toast('复制失败，请长按结果复制')}})}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),1800)}
render();
